# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 16.0
org_name: Shopinvader
org_slug: shopinvader
rebel_module_groups: []
repo_description: Odoo module for shopinvader api for carrier
repo_name: Odoo module for shopinvader api for carrier
repo_slug: odoo-shopinvader-carrier
repo_website: https://github.com/shopinvader/odoo-shopinvader-carrier
use_pyproject_toml: false
use_ruff: false

