sudo: false
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/pre-commit

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

language: python

stages:
  - linting
  - test

python:
  - "3.6"

jobs:
  include:
    - stage: linting
      name: "Pre-Commit"
      python: 3.6
      install: pip install pre_commit
      script: pre-commit run --all
env:
  global:
  - VERSION="12.0" TESTS="1" LINT_CHECK="0" ERRORS_IGNORE="Wrong HTTP_API_KEY;RESTFULL call to url" MQT_DEP="PIP"

  matrix:
  - TESTS="0" LINT_CHECK="1"
  - ODOO_REPO="odoo/odoo"
  - UNIT_TEST="1" ODOO_REPO="OCA/OCB"

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - printf '[options]\n\nrunning_env = dev\nkeychain_key_dev = HRdthrkXp28SCHX0kmwOgIob-82N-w8zWoE_UsctE7E=' > ${HOME}/.openerp_serverrc
  - export PATH=.travis:${PATH}

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
